---

- name: apt update
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: install packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - build-essential
    - htop
    - unzip
    - vim
    - git
