---

- name: apt update
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: install packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - build-essential
    - htop
    - unzip
    - vim
    - unbound
    - git
- name: setup unbound conf
  template: src=unbound.conf.j2 dest=/etc/unbound/unbound.conf
  sudo: yes
  notify:
    - restart unbound

- name: ensure conf is used for unbound
  lineinfile: dest=/etc/default/unbound regexp=^DAEMON_OPTS= 'line=DAEMON_OPTS="-c /etc/unbound/unbound.conf"'
  sudo: yes
  notify:
    - restart unbound
