---

- name: install finger service for consul
  template: src=finger.json.j2 dest=/etc/consul.d/finger.json
  notify:
    - restart consul

- name: copy finger folder
  copy: >
    src=finger
    dest=/root/go/src/github.com/longnguyen11288

- name: build finger
  shell: . /etc/profile && make
  args:
    chdir: /root/go/src/github.com/longnguyen11288/finger
