---
- hosts: arm-*
  roles:
    - common
    - { role: consul, sudo: yes }
    - { role: arms, sudo: yes }

- hosts: finger-*
  roles:
    - common
    - { role: consul, sudo: yes }
    - { role: fingers, sudo: yes }

- hosts: head
  roles:
    - common
    - { role: consul, sudo: yes }
    - { role: head, sudo: yes }
  vars:
    nginx_remove_default: true
    htpasswd:
      - name: consul
        users:
        - { name: admin, password: admin }
