---
# tasks file for consul
- name: downloads Consul package
  local_action: >
    get_url
      url="https://dl.bintray.com/mitchellh/consul/{{consul_version}}_linux_amd64.zip"
      dest="{{consul_download_dir}}"
  tags: download
  sudo: no

- name: downloads Consul UI package
  local_action: >
    get_url
      url="https://dl.bintray.com/mitchellh/consul/{{consul_version}}_web_ui.zip"
      dest="{{consul_download_dir}}"
  tags: download
  sudo: no
  when: consul_master == 'true'

- name: ensures {{consul_installation_dir}} exists
  file:
    path="{{consul_installation_dir}}"
    mode=0700
    state=directory

- name: ensures ui dir exists
  file:
    path="/opt/consul/ui"
    mode=0700
    state=directory
  when: consul_master == 'true'

- name: unpacks Consul UI to /opt/consul/ui
  unarchive:
    src="{{consul_download_dir}}/{{consul_version}}_web_ui.zip"
    dest="/opt/consul/ui"
  tags: unpack
  when: consul_master == 'true'

- name: unpacks Consul to {{consul_installation_dir}}
  unarchive:
    src="{{consul_download_dir}}/{{consul_version}}_linux_amd64.zip"
    dest="{{consul_installation_dir}}"
  tags: unpack

- name: ensures consul command has the right permissions
  file:
    path="{{consul_installation_dir}}/consul"
    mode=0700
    state=file

- name: ensures consul command is in the PATH
  lineinfile:
    dest=~/.bashrc
    line="export PATH={{consul_installation_dir}}:$PATH"
    state=present
    insertafter=EOF
    create=true

- name: consul master is true
  template: src=consul.j2 dest=/root/consul
  when: consul_master == 'true'

- name: setup consul init.d
  template: src=consul.j2 dest=/etc/init.d/consul

- name: create consul conf folder
  file: path=/etc/consul state=directory

- name: setup consul conf
  template: src=consul.json.j2 dest=/etc/consul/consul.json

- name: setup correct permission for init.d file
  file: path=/etc/init.d/consul mode=0700
  notify:
    - restart consul
